---
name: jetls
description: JETLS.jl is a Julia Enhanced Type-aware Language Server that provides advanced static analysis and seamless integration with the Julia runtime.
homepage: https://github.com/aviatesk/JETLS.jl
languages:
  - Julia
licenses:
  - MIT
categories:
  - LSP

source:
  id: pkg:github/aviatesk/JETLS.jl@2025-12-12
  build:
    - target: unix
      run: |
        julia --startup-file=no --project=. -e 'using Pkg; Pkg.instantiate()'
        mkdir -p bin
        cat > bin/jetls << 'EOF'
        #!/usr/bin/env sh
        # Follow symlinks to find the real script location
        SCRIPT="$0"
        while [ -L "$SCRIPT" ]; do
          SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT")" && pwd)"
          SCRIPT="$(readlink "$SCRIPT")"
          # If SCRIPT is relative, make it absolute
          case "$SCRIPT" in
            /*) ;;
            *) SCRIPT="$SCRIPT_DIR/$SCRIPT" ;;
          esac
        done

        SCRIPT_DIR="$(cd -P "$(dirname "$SCRIPT")" && pwd)"
        PROJECT_DIR="$SCRIPT_DIR/.."

        exec julia --startup-file=no --project="$PROJECT_DIR" -e 'using JETLS; JETLS.runserver(stdin, stdout)' "$@"
        EOF
        chmod +x bin/jetls
    - target: win
      run: |
        julia --startup-file=no --project=. -e 'using Pkg; Pkg.instantiate()'
        if not exist bin mkdir bin
        (
        echo @echo off
        echo julia --startup-file=no --project=%%~dp0.. -e "using JETLS; JETLS.runserver(stdin, stdout)" %%*
        ) > bin\jetls.cmd

bin:
  jetls: bin/jetls
