---
name: jetls
description: JETLS.jl is a Julia language server that provides advanced static analysis and seamless integration with the Julia runtime.
homepage: https://github.com/aviatesk/JETLS.jl
languages:
  - Julia
licenses:
  - MIT
categories:
  - LSP

source:
  id: pkg:github/ultimatile/jetls-sysimage@2026-05-06
  asset:
    - target: linux_x64
      file: jetls-sysimage-{{version}}-linux-x64.zip:libexec/
      bin: exec:libexec/bin/jetls
    - target: darwin_arm64
      file: jetls-sysimage-{{version}}-macos-arm64.zip:libexec/
      bin: exec:libexec/bin/jetls
    - target: win_x64
      file: jetls-sysimage-{{version}}-win-x64.zip:libexec/
      bin: libexec/bin/jetls.cmd

bin:
  jetls: "{{source.asset.bin}}"
