---
name: jetls
description: JETLS.jl is a Julia language server that provides advanced static analysis and seamless integration with the Julia runtime.
homepage: https://github.com/aviatesk/JETLS.jl
languages:
  - Julia
licenses:
  - MIT
categories:
  - LSP

source:
  id: pkg:github/aviatesk/JETLS.jl@2026-02-16
  build:
    - target: unix
      run: |
        set -e
        julia --startup-file=no -e 'using Pkg; Pkg.Apps.add(; url="https://github.com/aviatesk/JETLS.jl", rev="2026-02-16")'
        APP_BIN="$(julia --startup-file=no -e 'using Pkg; println(joinpath(first(Base.DEPOT_PATH), "bin", "jetls"))')"
        mkdir -p bin
        ln -sf "$APP_BIN" bin/jetls
    - target: win
      run: |
        setlocal enabledelayedexpansion
        julia --startup-file=no -e "using Pkg; Pkg.Apps.add(; url=\"https://github.com/aviatesk/JETLS.jl\", rev=\"2025-12-12\")"
        for /f "delims=" %%A in ('julia --startup-file=no -e "using Pkg; println(joinpath(first(Base.DEPOT_PATH), \"bin\", \"jetls.cmd\"))"') do set "APP_BIN=%%A"
        if not exist bin mkdir bin
        > bin\jetls.cmd (
        echo @echo off
        echo "%APP_BIN%" %%*
        )

bin:
  jetls: bin/jetls
